version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"

  kibana:
    image: kibana:latest
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"

  logstash:
    image: logstash:latest
    links:
      - elasticsearch
    volumes:
      - ./:/config-dir
    command: [-f, /config-dir/logstash.conf]
    ports:
      - "10200:10200"

  grafana:
    image: grafana/grafana:latest
    links:
      - elasticsearch
    ports:
      - "3000:3000"
