version: "2"

services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"

    networks:
      - default

  logstash:
    image: logstash:7.9.1
    links:
      - elasticsearch
    volumes:
      - ./logstash/:/config-dir
    command: [-f, /config-dir/logstash.conf]
    ports:
      - "10200:10200"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default

  kibana:
    image: kibana:7.9.1
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docker-elk.rule=Host(`${KIBANA_HOST}`)"
    networks:
      - default
      - web

networks:
  default:
  web:
    external: true
