version: '2'

services:
  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    image: logstash:5
    links:
      - elasticsearch
    volumes:
      - ./:/config-dir
    command: [-f, /config-dir/logstash.conf]
    ports:
      - "10200:10200"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: kibana:5
    links:
      - elasticsearch
    ports:
      - "5601:5601"
