input {
  beats {
    port => 10200
  }
}

filter {
  grok {
    patterns_dir => ["/config-dir/patterns"]
    match => {"message" => "%{RAILS4}"}
  }

  mutate {
    gsub => ["request_id", "[\[\]]", ""]
    replace => {"message" => "%{request_id} %{verb} %{request}"}
  }

  date {
      match => ["timestamp", "yyyy-MM-dd HH:mm:ss Z"]
  }
}

output {
  if [controller] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "%{[fields][index]}-%{+YYYY.MM.dd}"
      document_type => "%{[@metadata][type]}"
    }
  }
}
