input {
  beats {
    port => 10200
  }
}

filter {
  if [fields][format] == "json" {
    json {
      source => "message"
    }
  } else {
    grok {
      match => {
        "message" => "%{DATA:event} %{GREEDYDATA:msg}"
      }
    }
    kv {
      source => "msg"
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
  file {
    codec => line { format => "%{msg}" }
    path => "/var/log/logstash/%{event}.log"
  }
}
